let DB=null;
const overlay=document.getElementById('searchOverlay');
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
async function load(p){const r=await fetch(p);return r.json()}
async function init(){try{const [db,rel,timeline]=await Promise.all([load('data/seed.json'),load('data/relationships.json'),load('data/timeline.json')]);DB={...db,edges:rel.edges,timeline:timeline.entries};renderFilms();renderPeople();renderEvents();renderArchive();renderTimeline();renderGraph();filters();document.querySelector('.search-overlay p').textContent=DB.records.length+' records · '+DB.edges.length+' relationships · '+DB.version}catch(e){console.error(e)}}
function renderFilms(){const a=DB.records.filter(x=>x.entity_type==='film');document.getElementById('filmGrid').innerHTML=a.slice(0,6).map((x,i)=>'<article class="film film-'+i%3+'" data-open="'+x.id+'"><span class="year">'+(x.year||'—')+' · '+esc(x.status)+'</span><h3>'+esc(x.name)+'</h3><p>'+esc((x.language||[]).join(' · '))+'</p></article>').join('');bind()}
function renderPeople(){const a=DB.records.filter(x=>x.entity_type==='person');document.getElementById('peopleStrip').innerHTML=a.slice(0,4).map(x=>'<article class="person" data-open="'+x.id+'"><div class="portrait"></div><h3>'+esc(x.name)+'</h3><p>'+esc((x.roles||[]).join(' · ')||'FILM FRATERNITY')+'</p></article>').join('');bind()}
function renderEvents(){const a=DB.records.filter(x=>x.entity_type==='event');document.querySelector('.event-list').innerHTML=a.map(x=>'<article><time>'+esc(x.date||'UPCOMING')+'</time><div><h3>'+esc(x.name)+'</h3><p>'+esc(x.city||'Bihar')+'</p></div><a href="'+esc(x.sources?.[0]?.url||'#')+'" target="_blank">Source →</a></article>').join('')}
function renderArchive(filter='all',query=''){let a=DB.records;if(filter==='film'||filter==='person')a=a.filter(x=>x.entity_type===filter);else if(['Maithili','Bhojpuri','Magadhi','Angika'].includes(filter))a=a.filter(x=>(x.language||[]).includes(filter));else if(filter==='2000')a=a.filter(x=>(x.year||0)>=2000);if(query)a=a.filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase()));document.getElementById('resultsMeta').textContent=a.length+' records';document.getElementById('archiveResults').innerHTML=a.slice(0,50).map(x=>'<button class="archive-item" data-open="'+x.id+'"><span>'+esc(x.entity_type)+'</span><strong>'+esc(x.name)+'</strong><small>'+esc(x.year||x.city||x.district||'')+'</small></button>').join('');bind()}
function filters(){document.querySelectorAll('#filters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderArchive(b.dataset.filter)})}
function renderTimeline(){document.querySelector('.timeline-section .timeline').innerHTML=DB.timeline.sort((a,b)=>(a.year||0)-(b.year||0)).map(x=>'<div><b>'+x.year+' · '+esc(x.status)+'</b><span>'+esc(x.title)+'</span><p>'+esc(x.summary)+'</p></div>').join('')}
function renderGraph(){const s=document.getElementById('graphSvg'),ids=[...new Set(DB.edges.flatMap(e=>[e[0],e[1]]))].slice(0,20),pos={},by=Object.fromEntries(DB.records.map(x=>[x.id,x]));ids.forEach((id,i)=>{const a=i/ids.length*Math.PI*2;pos[id]=[500+400*Math.cos(a),210+155*Math.sin(a)]});s.innerHTML=DB.edges.filter(e=>pos[e[0]]&&pos[e[1]]).map(e=>'<line x1="'+pos[e[0]][0]+'" y1="'+pos[e[0]][1]+'" x2="'+pos[e[1]][0]+'" y2="'+pos[e[1]][1]+'"/>').join('')+ids.map(id=>'<g class="graph-node" data-open="'+id+'" transform="translate('+pos[id][0]+','+pos[id][1]+')"><circle r="5"/><text x="9" y="4">'+esc(by[id]?.name||id)+'</text></g>').join('');bind()}
function bind(){document.querySelectorAll('[data-open]').forEach(x=>x.onclick=()=>openRecord(x.dataset.open))}
function openRecord(id){const by=Object.fromEntries(DB.records.map(x=>[x.id,x])),r=by[id];if(!r)return;location.hash='#/'+r.entity_type+'/'+r.id;renderRecordPage(r)}
function renderRecordPage(r){const by=Object.fromEntries(DB.records.map(x=>[x.id,x])),related=DB.edges.filter(e=>e[0]===r.id||e[1]===r.id).map(e=>by[e[0]===r.id?e[1]:e[0]]).filter(Boolean);document.getElementById('recordOverlay')?.remove();const sourceHTML=(r.sources||[]).map(x=>'<a class="source-link" href="'+esc(x.url)+'" target="_blank" rel="noreferrer">'+esc(x.title)+' →</a>').join('');document.body.insertAdjacentHTML('beforeend','<div class="record-overlay record-page" id="recordOverlay"><button class="record-close" aria-label="Close">×</button><p class="eyebrow">'+esc(r.entity_type)+' · '+esc(r.status)+' · '+esc(r.confidence)+' confidence</p><h2>'+esc(r.name)+'</h2><p class="record-summary">'+esc(r.summary||'')+'</p><div class="record-meta">'+esc([r.year,r.city,r.district,...(r.language||[]),...(r.roles||[])].filter(Boolean).join(' · '))+'</div><h4>BIHAR CONNECTION</h4><p>'+esc((r.bihar_connections||[]).join(' · '))+'</p><h4>VERIFICATION</h4><p>Last checked: '+esc(r.last_verified||'Not recorded')+' · Research status: '+esc(r.status)+'</p><h4>RELATED RECORDS</h4><div class="related-records">'+(related.map(x=>'<button data-open="'+x.id+'">'+esc(x.name)+'</button>').join('')||'<p>No linked records yet.</p>')+'</div><h4>SOURCES</h4>'+sourceHTML+'</div>');document.querySelector('.record-close').onclick=()=>{history.pushState({},'',location.pathname+location.search);document.getElementById('recordOverlay')?.remove()};bind()}

document.getElementById('searchToggle').onclick=()=>{overlay.hidden=false;document.getElementById('searchInput').focus()};document.getElementById('searchClose').onclick=()=>overlay.hidden=true;document.addEventListener('keydown',e=>{if(e.key==='Escape'){overlay.hidden=true;document.getElementById('recordOverlay')?.remove()}});document.getElementById('searchInput').addEventListener('input',e=>{if(DB)renderArchive(document.querySelector('#filters .active')?.dataset.filter||'all',e.target.value.trim())});window.addEventListener('hashchange',()=>{const m=location.hash.match(/^#\/(film|person|place|organization|event)\/(.+)$/);if(m&&DB){const r=DB.records.find(x=>x.id===m[2]);if(r)renderRecordPage(r)}});init();